[platformio]
default_envs = esp32dev
include_dir = ../../firmware/include

[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    robtillaart/AS5600@0.6.7
    adafruit/Adafruit BNO08x@1.2.7
